[window_config]
title = "My Window"
size = [800, 600]

[sim_config]
desired_maximum_frame_latency = 10
star_count = 500000
arm_count = 4
galaxy_radius = 1000
spiralness = 0.005
noise_scale = 20
orbit_speed = 0.2
zoom_speed = 10.0